### PR TITLE
Wmass production full run2 10 6 26

### PR DESCRIPTION
**Pull request by sroychow**
I have added the following scripts. To setup, you need to follow the ```clone.sh``` script. However, you need to use the updated cmssw [branch](https://github.com/erc-asymow/cmssw/tree/WmassNanoProd_10_6_26_fullRun2).
Basically, in the setup script, replace 
```git cms-checkout-topic -u WMass:WmassNanoProd_$cmssw```
with 
```git cms-checkout-topic -u erc-asymow:WmassNanoProd_10_6_26_fullRun2``

Furthermore, one has to checkout this branch of WmassNanoProduction instead of the main one.

I have also added the feature of modifying the output path and site where the output NanoAOD will be written out. The default is 
```/store/group/cmst3/group/wmass/w-mass-13TeV/NanoAOD``` at ```T2_CH_CERN```. 

e.g, to write to your area at Pisa, 
```./scripts/prepareCrab.py -j1 -i inputs/data_2018.txt -v TrackRefit722 -p /store/user/sroychow/wmass-13-TeV -t T2_IT_Pisa```

### CODE REVIEW

**Comment by sroychow** [comment]
@bianchini @tanmayvb

**Comment by tanmayvb** [comment]
Is the there any MC config files corresponding to 2017 and 2018 ?

**Comment by sroychow** [comment]
@tanmayvb pushed MC scripts. To generate the configs for 2017/2018, 
```
./scripts/prepareCrab.py --makeConfig -j1 -i inputs/dyMC2017_v9.txt -v TrackRefit722
```
and similar.

**Comment by tanmayvb** [comment]
Thanks a lot and merging

**Pull request merged**
