### PR TITLE
Branch for full Run2 production

### PR DESCRIPTION
**Pull request by sroychow**
Clear PR now.
Contains
- updates to scripts for 2017/2018 production
Note - apart from the last commit, the others are coming since erc-asymow fork was not in sync with Wmass.

Before merging wishlist

- [ ] update setup script
- [x] update prepareCrab script to allow user input on storage site (default is CERN storage)

### CODE REVIEW

**Comment by sroychow** [comment]
@tanmayvb @mmusich  @bianchini  please check now. PR is clean with only the changes I made.

**Comment by mmusich** [comment]
@sroychow 

> updates to scripts for 2017/2018 production

Did you commit also the 2018 files? I don't see them in the branch. Any way I tested it with a trivial change of GlobalTag and era and runs out of the box

**Comment by tanmayvb** [comment]
Thanks, Shuvankar now it's fine to me

**Comment by sroychow** [comment]
closed in favour of #3

**Pull request closed without merging**
