### PR TITLE
Full run2 branch

### PR DESCRIPTION
**Pull request by sroychow**
Contains
- updates to scripts for 2017/2018 production
Note - apart from the last commit, the others are coming since erc-asymow fork was not in sync with Wmass.

Before merging wishlist
- update setup script
- update prepareCrab script to allow user input on storage site (default is CERN storage)

### CODE REVIEW

**Comment by tanmayvb** [comment]
It's better to keep the 2017 file only in the config folder

**Comment by tanmayvb** [comment]
Also would be better to remove all PostVFP tag , we don't need for 2017 and 2018

**Comment by sroychow** [comment]
> It's better to keep the 2017 file only in the config folder

Not clear to me. Can you explain? There will be another config to be added for 2018 as well in the config directory. 
 >> I mean to say all 2016 config files should be detected and only those config files and keeping only the 2017 and 2018 tag names. Also all names with VFP should remove

**Review by tanmayvb — COMMENTED** [review]
Lines 36 to 38 we don't need

**Comment by sroychow** [comment]
> Also would be better to remove all PostVFP tag , we don't need for 2017 and 2018

There will be no PostVFP tag for the 2017/18 configs. 
If you re referring to line 36-38 in ```prepareCrab.py``` - then the line 36-38 will still be needed to support 2016 production. In case of the 207-18, the if blocks above will be applicable. 

>> Now we have different branch foe 2016, 2017 and 2018 right?

**Comment by sroychow** [comment]
Probably the extra commits are creating confusion, let close this one and open another PR after I sync erc-asymow with Wmass.
>> Thanks, that will be great.

**Pull request closed without merging**
